- name: Deploy image
  hosts: run
  become: yes
  
  pre_tasks:
    - name: Ensure Git and Docker are installed on Debian
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - git
        - docker.io
        - python3-docker
      when: ansible_os_family == "Debian"

    - name: Ensure Git and Docker are installed on RedHat
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - git
        - docker
        - python-docker-py
      when: ansible_os_family == "RedHat"

    - name: Ensure Docker service is running
      service: name=docker state=started

  tasks:
    - name: Remove old container
      docker_container:
        name: run
        state: absent

    - name: Remove old image
      docker_image:
        name: "{{ app_image }}"
        state: absent
        
    - name: Run app container at production server
      docker_container:
        name: run
        image: "{{ app_image }}"
        ports: "8080:8080"
        recreate: yes